language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover

# SBOM configuration
jobs:
  include:
    - os: linux
      dist: focal
      addons:
        sbom:
          on:
            branch: main
          run_phase: after_success
          output_format: cyclonedx-json
          input_dir: /
          output_dir: /home/travis/build/build-tester-travis/travis-python/sbom-output

after_success:
  - echo "Build successful! Checking SBOM..."
  - ls -al /home/travis/build/build-tester-travis/travis-python/
  - cat /home/travis/build/build-tester-travis/travis-python/*

deploy:
  provider: releases
  edge: true
  file_glob: true
  file: /home/travis/build/build-ttester-travis/travis-python/*
  skip_cleanup: true
  on:
    branch: main
